### ISSUE TITLE
question regarding radar panel and wind direction plot (windrose)

### ISSUE THREAD

**Issue by peters77** [snuids/grafana-radar-panel#2]
Hi, 

I'm only a amateur user of grafana and access data from an InfluxDB containing my weather data.

Would it be possible to visualize wind direction and speed of a time period with your radar panel plugin like a windrose plot?

Here is an example.

Regards,

Christian 

![dvn_yearly](https://user-images.githubusercontent.com/8840918/32292311-f6f1ecb0-bf3f-11e7-8968-8b62e4541216.png)

**Comment by snuids** [comment]
Hi,

Unfortunately, your graph is more a bar graph displayed as a circle and not really a radar graph. The only thing you could try is to use an aggregation for the wind direction (0,10,20,...,360°) This way the axes coming from the center will become 0,10, e.t.c. and you will get a single shape that shows the max amplitude of the wind. 

If you define then one serie per wind speed threshold (2-5,5,7,...) you will get something that represents the same data, but it will not be as polished and clear as the graph you pasted there. (One radar shape per wind category)

Hope it helps,

Keep me informed if you achieve some results.

Cheers,

**Comment by Sineos** [comment]
For what its worth, here is how I did it:

![grafik](https://user-images.githubusercontent.com/4459312/65821233-1977c580-e233-11e9-9089-33137ed7726e.png)


![grafik](https://user-images.githubusercontent.com/4459312/65821180-732bc000-e232-11e9-971a-f54881433660.png)


Of course it does not have the "bar graph" style with the wind speed ranges, but my goal was to display the predominant wind directions over time.

An option to completely hide the radar graph's axis values would be nice, since in this example they do not have any real meaning.
