### ISSUE TITLE
upgrade to 1.3.0 not reflecting changes

### ISSUE THREAD

**Issue by laimaretto** [snuids/grafana-radar-panel#3]
Hi,

I've removed the 1.2.0 version and installed the new version as indicated (copy `dist` folder and rename to `radarpanel`) but I'm not seeing the new features in the options tab.

```
sudo ls /var/lib/grafana/plugins/ -l
total 24
drwxr-xr-x 4 root root 4096 oct 17 12:15 briangann-gauge-panel
drwxr-xr-x 5 root root 4096 sep 28 15:31 btplc-peak-report-panel
drwxr-xr-x 4 root root 4096 sep 28 15:30 grafana-piechart-panel
drwxr-xr-x 4 root root 4096 sep 25 10:36 mtanda-histogram-panel
drwxr-xr-x 4 root root 4096 oct 17 15:20 natel-plotly-panel
drwxr-xr-x 4 root root 4096 nov 10 18:36 radarpanel
```

I also tried to rename the `dist` folder as `snuids-radar-panel` but nothing happened ...

![image](https://user-images.githubusercontent.com/8891825/32679893-ec87b1a2-c646-11e7-8a74-8297c8c8316f.png)

![image](https://user-images.githubusercontent.com/8891825/32679904-ff142422-c646-11e7-998b-22210e3873e5.png)

Is there anything left to do?

Thanks!

**Comment by laimaretto** [comment]
Further, I see nothing now. An error appears on the panel.

![image](https://user-images.githubusercontent.com/8891825/32684070-e1280010-c65e-11e7-8fea-fdcc9d323d86.png)

I tried renaming the folder to `grafana-radar-panel`, restart the server, but nothing happens.

What to do now? ... :-(

**Comment by snuids** [comment]
@laimaretto

Hi, I had to change the id of the panel in order to be integrated in the Grafana panels (ids starting with grafana are reserved to grafana official panels). The new panel id is snuids-radar-panel.

Use the JSON panel edit option to change the id of the panel and your panel should reappear.

If you do not have the new options with the version 1.3, try to force a reload from the browser in order to clear the cache.

Sorry for the inconvenience.

Let me know if it helps.

Arnaud

![screen shot 2017-11-11 at 14 10 22](https://user-images.githubusercontent.com/13175107/32689758-3db5360a-c6ea-11e7-8505-3a416d77f47a.jpg)

![screen shot 2017-11-11 at 14 14 12](https://user-images.githubusercontent.com/13175107/32689776-b29c5d90-c6ea-11e7-82f2-c29d65b84128.jpg)

**Comment by laimaretto** [comment]
Hi!

So I solved it some how:

1) Stop grafana;
2) Remove folder;
3) Start grafana: with this I checked that there was no plugin in the GUI
4) Stop grafana;
5) Copy `dist` folder under plugins as `snuids-radar-panel`
6) Start grafana.

Following these steps solved my issue. Now, if I go on a panel, under JSON, I get to see what you recommend ...

![image](https://user-images.githubusercontent.com/8891825/32699779-cb20784c-c799-11e7-8972-de352480da01.png)

Thanks!

Lucas
